# Generated by Django 3.2 on 2021-12-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], max_length=8)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banks.bank')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banks.partner')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('requestmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests.requestmodelbase')),
                ('installments', models.PositiveIntegerField(default=0)),
                ('use', models.CharField(choices=[('GenerationIncome', 'Generationincome'), ('FamilyStrengthening', 'Familystrengthening'), ('Consumption', 'Consumption')], max_length=40)),
                ('use_detail', models.CharField(choices=[('Trade', 'Trade'), ('Smallcompany', 'Smallcompany'), ('HousingImprovement', 'Housingimprovement'), ('Education', 'Education'), ('HouseholdEquipment', 'Householdequipment'), ('Health', 'Health'), ('Debtpayment', 'Debtpayment'), ('ServicesPay', 'Servicespay'), ('FoodAndClothing', 'Foodandclothing'), ('Transport', 'Transport'), ('Travels', 'Travels'), ('Recreation', 'Recreation')], max_length=40)),
                ('payment_type', models.CharField(choices=[('advanceInstallments', 'Advanceinstallments'), ('installments', 'Installments')], max_length=40)),
            ],
            bases=('requests.requestmodelbase', models.Model),
        ),
        migrations.CreateModel(
            name='ShareRequest',
            fields=[
                ('requestmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requests.requestmodelbase')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            bases=('requests.requestmodelbase', models.Model),
        ),
    ]
