# Generated by Django 3.2 on 2022-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='paymentschedulerequest',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='sharerequest',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=100),
        ),
    ]
