version: 0.2

# env:
#   variables:
#     API_BASE: $API_BASE 


phases:
  # install:
  #  commands:

  pre_build:
    commands:
        - docker-compose -f local.yml build
        - docker-compose -f local.yml run --rm django python manage.py migrate
        - docker-compose -f local.yml run --rm django pytest
  pre_build:
    commands:
        - chmod 777 create-envs.sh
        - ./create-envs.sh
        - cat .envs/.production/.postgres
  build:
    commands:
        - docker-compose -f production.yml build
  
