version: 0.2

# env:
#   variables:
#      key: "value"
#      key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  # build:
  #   commands:
  #       - cd deployments/platformdeployment/Docker
  #       - docker-compose up -d
  install:
   commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command

  pre_build:
    commands:
        - docker-compose --version
        - chmod 777 create-envs.sh
        - ./create-envs.sh
  build:
    commands:
        - pwd
        - ls
        - cat .envs/.local/.postgres
        - cat .envs/.production/.postgres
        - docker-compose -f production.yml build
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths