version: 0.2

# env:
#   variables:
#      key: "value"
  #parameter-store:
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
  #git-credential-helper: yes

phases:
  # install:
  #  commands:
  pre_build:
    commands:
        - chmod 777 create-envs.sh
        - ./create-envs.sh
  build:
    commands:
        - docker-compose -f production.yml build
  
