# Generated by Django 3.2 on 2021-12-16 22:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on whict the object was created', verbose_name='create at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on whict the object was last modified', verbose_name='modified at')),
                ('phone_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format +9999999999. Up to 15 digits allowed', regex='\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('partner', 'Partner'), ('guest', 'Guest')], max_length=8)),
                ('temporal_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on whict the object was created', verbose_name='create at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on whict the object was last modified', verbose_name='modified at')),
                ('earnings', models.DecimalField(decimal_places=4, default=0.0, max_digits=100)),
                ('active_credit', models.DecimalField(decimal_places=4, default=0.0, max_digits=100)),
                ('shares', models.IntegerField(default=0)),
                ('document_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('scholarship', models.CharField(choices=[('noData', 'Nodata'), ('primary', 'Primary'), ('secundary', 'Secundary'), ('highschool', 'Highschool'), ('university', 'University'), ('master', 'Master'), ('doctorate', 'Doctorate')], default='noData', max_length=30)),
                ('birth_date', models.DateTimeField()),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banks.partner')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
