# Generated by Django 3.2 on 2021-12-17 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banks.bank'),
        ),
        migrations.AddField(
            model_name='bankrules',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banks.bank'),
        ),
        migrations.AddField(
            model_name='bank',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city'),
        ),
    ]
