# Generated by Django 3.2 on 2022-02-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrules',
            name='credit_investment_relationship',
            field=models.DecimalField(decimal_places=4, default=5, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bankrules',
            name='delay_interest',
            field=models.DecimalField(decimal_places=4, default=5.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bankrules',
            name='expenditure_fund_percentage',
            field=models.DecimalField(decimal_places=4, default=5.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bankrules',
            name='ordinary_interest',
            field=models.DecimalField(decimal_places=4, default=3.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='bankrules',
            name='reserve_fund_of_bad_debt_percentage',
            field=models.DecimalField(decimal_places=4, default=5.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='scheduleinstallment',
            name='interest_calculated',
            field=models.DecimalField(decimal_places=4, max_digits=100),
        ),
    ]
