# Generated by Django 3.2 on 2022-02-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdetail',
            name='profit_obtained',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=100),
        ),
    ]
