# Generated by Django 3.2 on 2022-03-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
