name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build the Docker images
      run: docker-compose -f local.yml build

    - name: Run Migrate
      run: docker-compose -f local.yml run --rm django python manage.py migrate 

    - name: Run test
      run: docker-compose -f local.yml run --rm django pytest
